### PR TITLE
Change "updated Plugin" to "Updated plugin"

### PR DESCRIPTION
**Pull request by TheGiraffe3**
"updated Plugin" seems less polished, and also is less grammatically correct.

Perhaps because it's script-generated, updated should stay decapitalized, but I think Plugin should definitely be non-capitalized.

@zuckung just confirming, this is the way to do it?

### CODE REVIEW

**Comment by zuckung** [comment]
ok lets see^^

first, README.md , res/allnews.md and mds/races.md are all script generated and a change there will be overwritten.

README.md will get generated out of res/template.txt, and the newsbox will get read out of res/news.txt(the upper 15 entries).
but after checking news.txt, i see it has just raw data, so just the script makemd.py create the relevant parts in README.md and allnews.md.

res/md/races your plugins, as you can see in the cronjob workflow, the update starts at 23:00 every day, so basically the last commit entry might be a day late.

then the checkdirectlinks.py, new_or_updated is a variable that, i think,  get checked later. might be better to make it uppercase by script later. need to check script more further.

so remove everything except the makemd.py  and the cronjob worklow with 00 to 0.

**Comment by zuckung** [comment]
ok, i ve read the script now.

```nline = ndate + " | " + nnew_or_update.title() + " plugin " + nname + " | Plugin got deleted or renamed <br>\n"```
(and same at the second line) in makemd.py should do the needed change. string.title() makes the first letter uppercase.

**Comment by TheGiraffe3** [comment]
Yep, for all the script generated ones, the script did the work.
"Plugin md generated": not a change I had planned, but the script made it.

**Comment by zuckung** [comment]
changes in checkdirectlinks.py needs to get reverted.

**Comment by TheGiraffe3** [comment]
Oof, those conflicts were _bad_.

**Comment by zuckung** [comment]
in case you want a repo like this to experiment with the code, it's not too hard to setup one. basically just the config.txt needs to get changed to fit to another repo. i m doing that too for testing, with just a few plugin files.

**Comment by zuckung** [comment]
maybe disable the cronjobs workflow in the fork? getting messages daily.

**Comment by TheGiraffe3** [comment]
Alright, I've removed the extraneous commits.

**Comment by TheGiraffe3** [comment]
And yep, workflows on my fork are now disabled temporarily so that conflicts don't take over again.

**Review by zuckung — APPROVED** [review]

**Pull request merged**
