### PR TITLE
more fixes

### PR DESCRIPTION
**Pull request by zuckung**
added informations to pluginlist file atlanteans.txt
fixed errorlog.txt getting pushed
fixed category "back to top" anchor links linking to wrong md

### CODE REVIEW

**Comment by TheGiraffe3** [comment]
It might be better to rename the file of the Atlanteans?
He didn't change anything when renaming to Oklen except the names, and the same thing happened with Arlug.

**Comment by zuckung** [comment]
hecter wants the plugin to be found by bith names.

**Comment by TheGiraffe3** [comment]
Should it also be findable by Oklen, because it was that briefly?

**Comment by zuckung** [comment]
probably yes.

i think this policy with plugins isn't really good, because the repo has already reached the 5gb limit of free repos. also it is not really my vision of a clean plugin list. but it is not my repo.

**Comment by TheGiraffe3** [comment]
> probably yes.
> 
> i think this policy with plugins isn't really good, because the repo has already reached the 5gb limit of free repos.

I've opened an issue to talk about this: #197.

> also it is not really my vision of a clean plugin list. but it is not my repo.

Well, I think it's an archive, and it makes sense for every known ES plugin to be in here.
Unless Hecter94 has to pay, which is not ideal.

**Comment by Hecter94** [comment]
> i think this policy with plugins isn't really good, because the repo has already reached the 5gb limit of free repos. also it is not really my vision of a clean plugin list. but it is not my repo.

If the size becomes an issue, we can look at cleaning up some old and/or duplicate files; until then, I see no downside to keeping them and no upside to removing them. This is supposed to be an archive after all, not a "clean plugin list"

**Pull request merged**
